In [4]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
            

In [5]:
subtract=np.subtract(x,y)
subtract

array([[-4., -4.],
       [-4., -4.]])

In [6]:
multiply=np.multiply(x,y)
multiply

array([[ 5., 12.],
       [21., 32.]])

In [7]:
divide=np.divide(x,y)
divide

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [13]:
inner=np.inner(x,y)
inner

array([[17., 23.],
       [39., 53.]])