In [11]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)


print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x/y)
print(np.divide(x,y))

print(x@y)
print(np.multiply(x,y))




[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19. 22.]
 [43. 50.]]
[[ 5. 12.]
 [21. 32.]]
