In [13]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)  
y= np.array([[5,6],[7,8]], dtype=np.float64)
print("subtraction x-y is:")
print(x-y)
print("multiplication x*y is: ")
print(x*y)
print("division x/y is: ")
print(x/y)
print("inner product is: ")
print(np.inner(x,y))

subtraction x-y is:
[[-4. -4.]
 [-4. -4.]]
multiplication x*y is: 
[[ 5. 12.]
 [21. 32.]]
division x/y is: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
inner product is: 
[[17. 23.]
 [39. 53.]]
