In [8]:
import numpy as np
x= np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)


In [17]:
result = np.subtract(x,y)
result
  

array([[-4., -4.],
       [-4., -4.]])

In [24]:
result = np.multiply(x,y)
result

array([[ 5., 12.],
       [21., 32.]])

In [25]:
result = np.divide(x,y)
result

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [27]:
result = np.dot(x,y)
result

array([[19., 22.],
       [43., 50.]])