In [1]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
            

In [18]:
subtract=np.subtract(x,y)
subtract

array([[-4., -4.],
       [-4., -4.]])

In [8]:
multiply=np.dot(x,y)
multiply

array([[19., 22.],
       [43., 50.]])

In [17]:
divide=np.divide(x,y)
divide

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [13]:
inner=np.inner(x,y)
inner

array([[17., 23.],
       [39., 53.]])