In [1]:
import numpy  
matrix=[[687,68,34],[89,77,82],[556,99,92]]
print(matrix) 
print("\n") 
print(numpy.transpose(matrix)) 

[[687, 68, 34], [89, 77, 82], [556, 99, 92]]


[[687  89 556]
 [ 68  77  99]
 [ 34  82  92]]
