# NUMPY

### Note: The x,y and numbers_ array are given at the bottom of this jupyter-notebook. Refer those arrays while solving issues.

## 1. Arrays in Numpy: 
NumPy’s main object is the homogeneous multidimensional array.

   a. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
    
   b. In NumPy dimensions are called axes. The number of axes is rank.
    
   c. NumPy’s array class is called ndarray. It is also known by the alias array.


In [13]:
#importing numpy
import numpy as np

In [14]:
mylist=[1,2,3]
arr=np.array(mylist)

In [15]:
arr

array([1, 2, 3])

In [16]:
arr_dimension=arr.ndim
arr_dimension

1

In [17]:
arr.size #gives the size of array

3

In [18]:
arr.dtype #tells the datatype of the array

dtype('int64')

##### Now, implement all these on a 2d-array

## 2. Array creation: 
There are various ways to create arrays in NumPy.

   a. For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
    
   b. Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.
    
   c. To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
    
   d. arange: returns evenly spaced values within a given interval. step size is specified.
    
   e. linspace: returns evenly spaced values within a given interval. num no. of elements are returned.
    
   f. Reshaping array: We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is:
    a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)
    
   g. Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.


### From list

In [19]:
mylist=[2,7]
np.array(mylist)

array([2, 7])

### From tuple

In [20]:
np.array((1 , 3, 2))

array([1, 3, 2])

### Other ways

In [21]:
np.arange(0,10,3)
#0->start(inclusive) 10->stop(exclusive) 1->step

array([0, 3, 6, 9])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.full((3, 3), 6,)
# Create a constant value array

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
np.linspace(0,5,10)
#0->start 5->end 10->no. of points evenly spaced between 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
arr3 = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
  
newarr = arr3.reshape(2, 2, 3)
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [27]:
np.random.rand(5)
#gives 5 random nos between 0-1

array([0.71718568, 0.97075597, 0.33369284, 0.22984723, 0.44179234])

## 3. Array Indexing

### Slicing: 
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


### Integer array indexing: 
In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [29]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


### Boolean array indexing: 
This method is used when we want to pick elements from array which satisfy some condition.

### 4. Operations on Arrays

There are various cool mathematical stuff which can be performed on numpy arrays. Since most of them can't be covered below, we will be giving issues regarding.

In [30]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [31]:
numbers_=[[687,68,34],[89,77,82],[556,99,92]]
np.array(numbers_)

array([[687,  68,  34],
       [ 89,  77,  82],
       [556,  99,  92]])